DATA_DIR = data

# TODO: define an all task that builds the finished output
# all:

# TODO: Use count_connections.py to generate a JSON file of all the counts of who emailed each other

# TODO: Figure out how to run parse_from_to.py on all the email files

# TODO: Figure out how to split up text of all emails

# TODO: Convert PDF to text to make parsing easier, probably use pdftotext
$(DATA_DIR)/all_emails.txt : $(DATA_DIR)/all_emails.pdf
